require:
  - rubocop-rspec

RSpec/ExampleLength:
  Max: 10

RSpec/FilePath:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 4

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/FrozenStringLiteralComment:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes
